# Generated by Django 3.2.5 on 2021-07-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('relative_coor_north', models.FloatField()),
                ('relative_coor_west', models.FloatField()),
                ('read_date', models.DateTimeField()),
                ('read_value', models.FloatField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
